version: '3.3'

services:
  memcached:
    image: memcached
    restart: always
    ports:
      - '11211'
  php:
    build: .docker/php-7.4/
    volumes:
      - ./web:/var/app
      - '.docker/php/php.ini:/etc/php/7.4/fpm/php.ini'
    environment:
      TZ: Asia/Taipei
    ports:
      - '9000'


  nginx:
    build: .docker/nginx/
    depends_on:
      - php
    ports:
      - '9910:80'
    links:
      - php
    volumes:
      - ./web:/var/app

  mysqldb:
    image: mariadb
    restart: always
    env_file:
      - '.env'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MAX_CONNECTIONS=1024
    ports:
      - '3306'
    volumes:
      - './DB/mysql:/var/lib/mysql'
      - '.docker/mysql/conf:/etc/mysql/conf.d'
    command: mysqld --sql_mode="" --innodb-large-prefix=on --innodb-file-format=barracuda --innodb-file-per-table=on

  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '9911:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysqldb
      - UPLOAD_LIMIT= 300000000
    depends_on:
      - mysqldb

  mongodb:
    image: library/mongo:3.4.9
    volumes:
      - ./DB/mongodb:/data/db
      - ./DB/backup:/backup
    command: mongod --auth
    ports:
      - '27017'
    privileged: true
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      TZ: Asia/Taipei
